site_name: nlmfedcred
nav:
  - About: index.md
  - Installation: install.md
  - Configuration: config.md
  - How To: howto.md
  - Trouble Shooting: trouble.md
  - Smartcard Utility: smartcard.md
plugins:
  - search
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
theme: readthedocs
repo_name: BitBucket
repo_url: https://git-scm.nlm.nih.gov/projects/CS/repos/nlmfedcred/
site_author: Dan Davis
site_description: A command-line supported federated AWS authentication through NIH Login
